Repository SunRiseGG/CourseWork2020, pull requests merged in 2020-06, with the labels that each got.

#7 Basic functionality
  app.js
  mailer.js
  package.json
  reader.js
  utils.js
Labels: core

#9 Database
  app.js
  database.js
  database.sql
  package.json
  queryBuilder.js
  utils.js
Labels: core, enhancement

#10 Fixes
  .eslintrc.json
  app.js
  database.js
  database.sql
  mailer.js
  queryBuilder.js
  reader.js
  utils.js
Labels: bug, core
